repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-executables-have-shebangs

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
        files: \.(sh|bash)$
        exclude: ^(scripts/|lib/|hooks/).*test.*\.sh$

  - repo: local
    hooks:
      - id: security-scan
        name: Custom Security Scan
        entry: ./scripts/security_scan.sh
        language: script
        files: \.(sh|bash|json|md|env)$
        pass_filenames: false
        always_run: true
